language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler
deploy:
  provider: heroku
  app: bezpieczna-przystan
  api_key:
    secure: erqBZEHsnmM2vdp++5WRSTNNVUtWTWzRJAGheMSXOTgcM5X5dIWrMcJivysGFmxhg49gKqmMqJxGH/p/5rCJu/e+HVvhEWdLf59K14YSxvizxB4yuKvp5hh3vb6ExW1vX57n8XteZwQjN9uLm9Itq04xHqOidm/y2TH8UnnCNTHghOpMSnyyZzFzwMdOpTkODK7TbBW/AqtbuR2GWVww5kYy3eEmteCZaWpcYwf0XjZW8JMurv+hJuR34FkGMdE2jWdJCcKagowddNVd0vxLO2jhD27K+XKRrT06xeqN0HuSzg3h8SlEI6nuQYopgxmbLUaWLS3rEw42ypB8bF2ln5ctzdGKmuJSNTUnfh7c7oIYvEU+YnT/J41D/Wyw2KvbJWtZiJIYjQ3vrwUSPZPiNKRSBO8qCntDA2lJfel+mWK6vswL2KlyQKU4EZqJcBF+CFxah+/1Zmxw4QmfOfYFrmIHXamNk9M2HHOhlqZBSWLjo/LlWlIznsivF+BSqsElT6Xg1xkySU+XzcTkaL+rIIFdIm7Cy+rYhNYE3v3CvXTs8TPWAfKP531GoTM7II6F9jh+8HbixUs/Hxe4g3k1Rr5yxK8ShAwhvZrqQ4VFoFASQ5F6uZJbn4tCvC+79TN+rmdCIblB5fzNXoid97cXVwe0Sxq5o219+zxBaHRGros=
  run: rake db:migrate
